### ISSUE TITLE
Comented code

### ISSUE THREAD

**Issue by israel05** [oxesoft/keyboardscanner#1]
Hi! It would be nice to have a comented code and also, if you could provide any fritzing (wiring) diagram would be awesome.

**Comment by godbless876** [comment]
Yeah a diagram would be great

**Comment by godbless876** [comment]
Can i use an 88 key keybed instead? Would it work?

**Comment by godbless876** [comment]
Can i use an 88 key keybed instead? Would it work?

**Comment by oxesoft** [comment]
Sure! You just need to find out your keyboard's wiring pattern. There is no recipe. You need to use a multimeter and a piece of paper. The only certainty is that every keyboard is a matrix.

**Comment by godbless876** [comment]
Ok.. well. I assembled everything but its not working.. can u do a
schematic of what u did so i can understand.

**Comment by godbless876** [comment]
Hey. I dont know what am doing wrong but its not working out very great for me.. not a beep. I hooked up the wires directly to the Arduino mega and nothing.. is it that i need to use pull down resistors at the input pins (or outputs):?.. idk

**Comment by oxesoft** [comment]
Hi. The input pins already have a pull up resistor and the code is enabling it (see lines 108 and 110 on rev 0b3109d). Take a look at [https://www.arduino.cc/en/Tutorial/DigitalPins](url)

**Comment by godbless876** [comment]
Ok.. I'll have a look and try again.
