### ISSUE TITLE
Working with Logic Pro X

### ISSUE THREAD

**Issue by hyfinn** [oxesoft/keyboardscanner#5]
Hi there,

Thanks so much for your work on this project. I'm excited to be converting some E-mu Xboards.

I wondered what you need to do to get a Mac to recognise the Arduino as a midi device and to get it working with DAWs like Logic Pro X?

Any advice is greatly appreciated. Thanks!
~Finn

**Comment by hyfinn** [comment]
@oxesoft Hi there, just wondered if you had a chance to look at the above? Cheers ~Finn

**Comment by oxesoft** [comment]
Hi. You could use [MIDIUSB](https://github.com/arduino-libraries/MIDIUSB) project or even use [Hairless MIDI<->Serial Bridge](https://projectgus.github.io/hairless-midiserial/).

**Comment by godbless876** [comment]
Hey.. I have a Yamaha psr3000 keybed..  it Outputs from a single ic....5
pins, gnd, vcc, clock, data and reset pins... How could I use this to work
with the Arduino/teensy..  and could I use this with another set of keys
also?

**Comment by oxesoft** [comment]
Can you read the IC spec? If yes, you can put this on Google and find out the spec sheet, otherwise, you can inspect the data signal with an osciloscope to find out how to deal with it.

**Comment by godbless876** [comment]
I don't have an ociloscope..
And I cant find any data on the chip.. .. psr3000 service manual does show
a pinout of the chip tho... But no details of it's operation

**Comment by godbless876** [comment]
So I found the docs on the chip... Don't have a clue of how to read it.. I think it's i2c connection but the PC doesn't see it... Also I have another keybey trying to use however I am not getting no signal... Tried the din midi out and nothing... I switched around all the diodes and nothing.. idk what I am doing wrong.. is it supposed to be used with a din? Or USB?
