### ISSUE TITLE
Ligação dos fios no arduino

### ISSUE THREAD

**Issue by seileremerson** [oxesoft/keyboardscanner#7]
Ola Daniel, muito legal seu projeto.
Estou querendo fazer ele com um casio ctk 485 61 teclas que comprei com defeito. Porém não entendi  como ligar o cabo das teclas no arduino.
Sou um iniciante na eletrônica, vi que seu código referencia algumas posições no arduino, mas não consegui me localizar.
O cabo do meu teclado possui 16 fios e o seu código mostra alguns a mais.
Outra coisa tenho um arduino mega 2560, posso usar esse mesmo?
Além dessas dúvidas não sei qual software devo instalar no computador para gerenciar os sons e tocar.

"byte output_pins[] = {
    38,
    40,
    42,
    44,
    46,
    23,
    25,
    27
};
byte input_pins[] = {
    22, 24,
    26, 28,
    30, 32,
    34, 36,
    29, 31,
    33, 35,
    37, 39,
    41, 43 "

**Comment by oxesoft** [comment]
Olá. Sim, vc pode e deve usar o Arduino Mega 2560. Não tem como vc escapar
de entender qual é o padrão da dupla matriz, testando as teclas com o
multímetro e entendendo o código para poder configurar os pinos. Sobre o
software, eu indico o http://reaper.fm/ e diversos plugins de instrumentos
virtuais que vc pode baixar gratuitamente. Os muito bons normalmente são
pagos. São muitos mesmo.

Daniel Moura
@danielgvmoura <http://twitter.com/danielgvmoura>
oxesoft@gmail.com
http://www.oxesoft.com


Em qua., 1 de abr. de 2020 às 18:20, seileremerson <notifications@github.com>
escreveu:

**Comment by seileremerson** [comment]
Sim sim, é o que estou tentando compreender, o procedimento para ligar.
Qual seria esse procedimento com o multímetro e como ele se relaciona com as entradas do arduino?
Tenho o esquema da matriz do manual de serviço, não sei se ajuda.
https://drive.google.com/file/d/1TGL9TPSyXwyCuUAh00MxrbGivFmqURsn/view?usp=sharing

**Comment by oxesoft** [comment]
Ajuda sim! Pelo jeito KO0 até KO12 e KI0 até KI7 são os fios do cabo flat. Acredito que seu teclado não tenha velocidade. Você precisaria alterar o código para "desligar" a medição de velocidade. Não tenho um outro projeto pra lhe indicar.
